#!/usr/bin/env node

// Generate deterministic NMEA sentences for the BLE transfer benchmark.
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const valueFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : Number(args[index + 1]);
};
const pathFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : args[index + 1];
};

const durationSeconds = valueFor("--duration-seconds", 70);
const frequencyHz = valueFor("--frequency-hz", 10);
const headerOutput = pathFor("--header-output", "firmware/BleTestEsp32/route_data.h");
const rawOutput = pathFor("--raw-output", "route_gps.csv");

if (!Number.isInteger(durationSeconds) || durationSeconds < 1 || !Number.isInteger(frequencyHz) || frequencyHz < 1) {
  console.error("duration and frequency must be positive integers");
  process.exit(1);
}

const totalPoints = durationSeconds * frequencyHz;
const lines = [];
const originLat = 52.2297;
const originLon = 21.0122;

function nmeaCoordinate(value, latitude) {
  const absolute = Math.abs(value);
  const degrees = Math.floor(absolute);
  const minutes = (absolute - degrees) * 60;
  const degreeWidth = latitude ? 2 : 3;
  return `${degrees.toString().padStart(degreeWidth, "0")}${minutes.toFixed(4).padStart(7, "0")}`;
}

function nmeaSentence(body) {
  let checksum = 0;
  for (const character of body) checksum ^= character.charCodeAt(0);
  return `$${body}*${checksum.toString(16).toUpperCase().padStart(2, "0")}\r\n`;
}

function nmeaTime(timestampMs) {
  const totalCentiseconds = Math.floor(timestampMs / 10);
  const hours = Math.floor(totalCentiseconds / 360000) % 24;
  const minutes = Math.floor(totalCentiseconds / 6000) % 60;
  const seconds = Math.floor(totalCentiseconds / 100) % 60;
  const centiseconds = totalCentiseconds % 100;
  return `${hours.toString().padStart(2, "0")}${minutes.toString().padStart(2, "0")}${seconds.toString().padStart(2, "0")}.${centiseconds.toString().padStart(2, "0")}`;
}

for (let point = 0; point < totalPoints; point += 1) {
  const timestamp = Math.floor(point * 1000 / frequencyHz);
  const phase = timestamp / 900000 * 2 * Math.PI;
  const latitude = originLat + 0.012 * Math.sin(phase) + 0.002 * Math.sin(phase * 3);
  const longitude = originLon + 0.018 * Math.cos(phase) + 0.003 * Math.cos(phase * 2);
  const time = nmeaTime(timestamp);
  const latitudeDirection = latitude < 0 ? "S" : "N";
  const longitudeDirection = longitude < 0 ? "W" : "E";
  const latitudeField = nmeaCoordinate(latitude, true);
  const longitudeField = nmeaCoordinate(longitude, false);

  lines.push(nmeaSentence(
    `GPRMC,${time},A,${latitudeField},${latitudeDirection},${longitudeField},${longitudeDirection},005.4,084.4,010126,,,A`,
  ));
  lines.push(nmeaSentence(
    `GPGGA,${time},${latitudeField},${latitudeDirection},${longitudeField},${longitudeDirection},1,10,0.9,100.0,M,46.9,M,,`,
  ));
}

const raw = Buffer.from(lines.join(""), "ascii");
let crc32 = 0xFFFFFFFF;
for (const byte of raw) {
  crc32 ^= byte;
  for (let bit = 0; bit < 8; bit += 1) {
    crc32 = (crc32 >>> 1) ^ (0xEDB88320 & -(crc32 & 1));
  }
}
crc32 = (~crc32) >>> 0;

const csvLiterals = [];
for (let index = 0; index < raw.length; index += 120) {
  csvLiterals.push(JSON.stringify(raw.toString("ascii", index, index + 120)));
}

const header = `#pragma once

#include <Arduino.h>

// Generated by tools/generate_route.js. Do not edit manually.
static const uint32_t GPS_ROUTE_POINT_COUNT = ${totalPoints}UL;
static const uint32_t GPS_ROUTE_LINE_COUNT = ${lines.length}UL;
static const uint32_t GPS_ROUTE_RAW_SIZE = ${raw.length}UL;
static const uint32_t GPS_ROUTE_CRC32 = 0x${crc32.toString(16).toUpperCase()}UL;
static const char GPS_ROUTE_CSV[] PROGMEM =
${csvLiterals.join("\n")};
`;

fs.mkdirSync(path.dirname(headerOutput), { recursive: true });
fs.mkdirSync(path.dirname(rawOutput), { recursive: true });
fs.writeFileSync(rawOutput, raw);
fs.writeFileSync(headerOutput, header, "ascii");

console.log(`points: ${totalPoints}`);
console.log(`NMEA lines: ${lines.length}`);
console.log(`raw: ${raw.length} bytes`);
console.log(`CRC32: ${crc32.toString(16).toUpperCase().padStart(8, "0")}`);
console.log(`header: ${headerOutput}`);
console.log(`raw file: ${rawOutput}`);
