#!/usr/bin/env node

// Generate a deterministic, slowly changing GPS route for the BLE transfer test.
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const valueFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : Number(args[index + 1]);
};
const pathFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : args[index + 1];
};

const durationSeconds = valueFor("--duration-seconds", 300);
const frequencyHz = valueFor("--frequency-hz", 10);
const headerOutput = pathFor("--header-output", "firmware/BleTestEsp32/route_data.h");
const rawOutput = pathFor("--raw-output", "route_gps.csv");

if (!Number.isInteger(durationSeconds) || durationSeconds < 1 || !Number.isInteger(frequencyHz) || frequencyHz < 1) {
  console.error("duration and frequency must be positive integers");
  process.exit(1);
}

const totalPoints = durationSeconds * frequencyHz;
const lines = ["t_ms,latitude,longitude\n"];
const deltaLines = ["t_ms,latitude,longitude\n"];
const originLat = 52.2297;
const originLon = 21.0122;
let previousPoint = null;

for (let point = 0; point < totalPoints; point += 1) {
  const seconds = point / frequencyHz;
  // A smooth loop with small variations, roughly resembling a moving track.
  const phase = seconds / 900 * 2 * Math.PI;
  const latitude = originLat + 0.012 * Math.sin(phase) + 0.002 * Math.sin(phase * 3);
  const longitude = originLon + 0.018 * Math.cos(phase) + 0.003 * Math.cos(phase * 2);
  const timestamp = Math.floor(point * 1000 / frequencyHz);
  const latitudeScaled = Math.round(latitude * 1e6);
  const longitudeScaled = Math.round(longitude * 1e6);
  lines.push(`${timestamp},${(latitudeScaled / 1e6).toFixed(6)},${(longitudeScaled / 1e6).toFixed(6)}\n`);
  if (previousPoint === null) {
    deltaLines.push(`${timestamp},${latitudeScaled},${longitudeScaled}\n`);
  } else {
    deltaLines.push(`${timestamp - previousPoint.timestamp},${latitudeScaled - previousPoint.latitude},${longitudeScaled - previousPoint.longitude}\n`);
  }
  previousPoint = { timestamp, latitude: latitudeScaled, longitude: longitudeScaled };
}

const raw = Buffer.from(lines.join(""), "ascii");
const delta = Buffer.from(deltaLines.join(""), "ascii");
const decodedLines = [deltaLines[0]];
let decodedPoint = null;
for (const encodedLine of deltaLines.slice(1)) {
  const [timeValue, latitudeValue, longitudeValue] = encodedLine.trim().split(",").map(Number);
  if (decodedPoint === null) {
    decodedPoint = { timestamp: timeValue, latitude: latitudeValue, longitude: longitudeValue };
  } else {
    decodedPoint.timestamp += timeValue;
    decodedPoint.latitude += latitudeValue;
    decodedPoint.longitude += longitudeValue;
  }
  decodedLines.push(`${decodedPoint.timestamp},${(decodedPoint.latitude / 1e6).toFixed(6)},${(decodedPoint.longitude / 1e6).toFixed(6)}\n`);
}
if (decodedLines.join("") !== lines.join("")) throw new Error("delta encoding verification failed");
let crc32 = 0xFFFFFFFF;
for (const byte of raw) {
  crc32 ^= byte;
  for (let bit = 0; bit < 8; bit += 1) {
    crc32 = (crc32 >>> 1) ^ (0xEDB88320 & -(crc32 & 1));
  }
}
crc32 = (~crc32) >>> 0;
const deltaLiterals = [];
for (let index = 0; index < delta.length; index += 120) {
  deltaLiterals.push(JSON.stringify(delta.toString("ascii", index, index + 120)));
}

const header = `#pragma once

#include <Arduino.h>

// Generated by tools/generate_route.js. Do not edit manually.
static const uint32_t GPS_ROUTE_POINT_COUNT = ${totalPoints}UL;
static const uint32_t GPS_ROUTE_RAW_SIZE = ${raw.length}UL;
static const uint32_t GPS_ROUTE_CRC32 = 0x${crc32.toString(16).toUpperCase()}UL;
static const uint32_t GPS_ROUTE_DELTA_SIZE = ${delta.length}UL;
static const char GPS_ROUTE_DELTA[] PROGMEM =
${deltaLiterals.join("\n")};
`;

fs.mkdirSync(path.dirname(headerOutput), { recursive: true });
fs.mkdirSync(path.dirname(rawOutput), { recursive: true });
fs.writeFileSync(rawOutput, raw);
fs.writeFileSync(headerOutput, header, "ascii");

console.log(`points: ${totalPoints}`);
console.log(`raw: ${raw.length} bytes`);
console.log(`delta: ${delta.length} bytes`);
console.log(`compression ratio: ${(raw.length / delta.length).toFixed(2)}x`);
console.log("delta verification: OK");
console.log(`header: ${headerOutput}`);
console.log(`raw file: ${rawOutput}`);
