#!/usr/bin/env node

// Generate a deterministic, slowly changing GPS route for the BLE transfer test.
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const valueFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : Number(args[index + 1]);
};
const pathFor = (name, fallback) => {
  const index = args.indexOf(name);
  return index === -1 ? fallback : args[index + 1];
};

const durationSeconds = valueFor("--duration-seconds", 300);
const frequencyHz = valueFor("--frequency-hz", 10);
const headerOutput = pathFor("--header-output", "firmware/BleTestEsp32/route_data.h");
const rawOutput = pathFor("--raw-output", "route_gps.csv");

if (!Number.isInteger(durationSeconds) || durationSeconds < 1 || !Number.isInteger(frequencyHz) || frequencyHz < 1) {
  console.error("duration and frequency must be positive integers");
  process.exit(1);
}

const totalPoints = durationSeconds * frequencyHz;
const lines = ["t_ms,latitude,longitude\n"];
const originLat = 52.2297;
const originLon = 21.0122;

for (let point = 0; point < totalPoints; point += 1) {
  const seconds = point / frequencyHz;
  // A smooth loop with small variations, roughly resembling a moving track.
  const phase = seconds / 900 * 2 * Math.PI;
  const latitude = originLat + 0.012 * Math.sin(phase) + 0.002 * Math.sin(phase * 3);
  const longitude = originLon + 0.018 * Math.cos(phase) + 0.003 * Math.cos(phase * 2);
  const timestamp = Math.floor(point * 1000 / frequencyHz);
  const latitudeScaled = Math.round(latitude * 1e6);
  const longitudeScaled = Math.round(longitude * 1e6);
  lines.push(`${timestamp},${(latitudeScaled / 1e6).toFixed(6)},${(longitudeScaled / 1e6).toFixed(6)}\n`);
}

const raw = Buffer.from(lines.join(""), "ascii");
const rawText = raw.toString("ascii");
const csvLiterals = [];
for (let index = 0; index < rawText.length; index += 120) {
  csvLiterals.push(JSON.stringify(rawText.slice(index, index + 120)));
}

const header = `#pragma once

#include <Arduino.h>

// Generated by tools/generate_route.js. Do not edit manually.
static const uint32_t GPS_ROUTE_POINT_COUNT = ${totalPoints}UL;
static const uint32_t GPS_ROUTE_RAW_SIZE = ${raw.length}UL;
static const char GPS_ROUTE_CSV[] PROGMEM =
${csvLiterals.join("\n")};
`;

fs.mkdirSync(path.dirname(headerOutput), { recursive: true });
fs.mkdirSync(path.dirname(rawOutput), { recursive: true });
fs.writeFileSync(rawOutput, raw);
fs.writeFileSync(headerOutput, header, "ascii");

console.log(`points: ${totalPoints}`);
console.log(`raw: ${raw.length} bytes`);
console.log("compression: performed on ESP32 with miniz tdefl");
console.log(`header: ${headerOutput}`);
console.log(`raw file: ${rawOutput}`);
